"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Circle_1 = require("./Circle");
var Rectangle_1 = require("./Rectangle");
var Shape_1 = require("./Shape");
var myShape = new Shape_1.Shape(10, 15);
console.log(myShape.getInfo());
var myCircle = new Circle_1.Circle(10, 15, 20);
console.log(myCircle.getInfo());
var myRec = new Rectangle_1.Rectangle(5, 10, 15, 20);
console.log(myRec.getInfo());
